//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrisonTrade.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class bugDesc
    {
        public int id { get; set; }
        public Nullable<int> id_bug { get; set; }
        public string description { get; set; }
    
        public virtual bug bug { get; set; }
    }
}
