//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrisonTrade.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrisonEntity : DbContext
    {
        public PrisonEntity()
            : base("name=PrisonEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bug> bug { get; set; }
        public virtual DbSet<bugDesc> bugDesc { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Guild> Guild { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Prison> Prison { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trade> Trade { get; set; }
    }
}
