//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrisonTrade.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int id { get; set; }
        public Nullable<int> id_PeopGive { get; set; }
        public Nullable<int> id_PeopTake { get; set; }
        public Nullable<int> id_Guild { get; set; }
        public Nullable<int> id_Bug { get; set; }
    
        public virtual bug bug { get; set; }
        public virtual Guild Guild { get; set; }
        public virtual People People { get; set; }
        public virtual People People1 { get; set; }
    }
}
